    - name: Trigger Azure ML job
      uses: azure/CLI@v2
      with:
        inlineScript: |
          az extension add -n ml --yes
          az configure --defaults \
            group=shivamrane2005-rg \
            workspace=Shivam
          az ml job create --file azureml/train-job.yml

